export const entries = [
  { country: "Argentina", capital: "Buenos Aires" },
  { country: "Australia", capital: "Canberra" },
  { country: "Austria", capital: "Vienna" },
  { country: "Belgium", capital: "Brussels" },
  { country: "Brazil", capital: "Brasília" },
  { country: "Canada", capital: "Ottawa" },
  { country: "Chile", capital: "Santiago" },
  { country: "China", capital: "Beijing" },
  { country: "Colombia", capital: "Bogotá" },
  { country: "Czech Republic", capital: "Prague" },
  { country: "Denmark", capital: "Copenhagen" },
  { country: "Egypt", capital: "Cairo" },
  { country: "Finland", capital: "Helsinki" },
  { country: "France", capital: "Paris" },
  { country: "Germany", capital: "Berlin" },
  { country: "Greece", capital: "Athens" },
  { country: "Hungary", capital: "Budapest" },
  { country: "India", capital: "New Delhi" },
  { country: "Indonesia", capital: "Jakarta" },
  { country: "Ireland", capital: "Dublin" },
  { country: "Israel", capital: "Jerusalem" },
  { country: "Italy", capital: "Rome" },
  { country: "Japan", capital: "Tokyo" },
  { country: "Kenya", capital: "Nairobi" },
  { country: "Mexico", capital: "Mexico City" },
  { country: "Netherlands", capital: "Amsterdam" },
  { country: "New Zealand", capital: "Wellington" },
  { country: "Nigeria", capital: "Abuja" },
  { country: "Norway", capital: "Oslo" },
  { country: "Pakistan", capital: "Islamabad" },
  { country: "Peru", capital: "Lima" },
  { country: "Poland", capital: "Warsaw" },
  { country: "Portugal", capital: "Lisbon" },
  { country: "South Africa", capital: "Pretoria" },
  { country: "South Korea", capital: "Seoul" },
];
